BEGIN TRANSACTION;
CREATE TABLE `DS_MAG_BAG` (
	`BAG_ABBREV`	TEXT NOT NULL,
	`BAG_NM`	TEXT NOT NULL,
	`MAGIC_POWER_DESCR`	TEXT,
	`SORT_ORD`	INTEGER,
	`LAST_UPDATE_DTTM`	TEXT,
	`LAST_UPDATE_INITIALS`	TEXT,
	PRIMARY KEY(BAG_ABBREV)
);
INSERT INTO `DS_MAG_BAG` (BAG_ABBREV,BAG_NM,MAGIC_POWER_DESCR,SORT_ORD,LAST_UPDATE_DTTM,LAST_UPDATE_INITIALS) VALUES ('CANBAG','Canoe Bag',NULL,NULL,NULL,NULL);
INSERT INTO `DS_MAG_BAG` (BAG_ABBREV,BAG_NM,MAGIC_POWER_DESCR,SORT_ORD,LAST_UPDATE_DTTM,LAST_UPDATE_INITIALS) VALUES ('FSH','Magic Fish Sack',NULL,NULL,NULL,NULL);
INSERT INTO `DS_MAG_BAG` (BAG_ABBREV,BAG_NM,MAGIC_POWER_DESCR,SORT_ORD,LAST_UPDATE_DTTM,LAST_UPDATE_INITIALS) VALUES ('ESC','Escalator Bag',NULL,NULL,NULL,NULL);
COMMIT;
