BEGIN TRANSACTION;
CREATE TABLE "DS_MAG_BAG" (
	"BAG_ABBREV" VARCHAR(18) NOT NULL, 
	"BAG_NM" VARCHAR(128), 
	"MAGIC_POWER_DESCR" VARCHAR(256), 
	"SORT_ORD" INTEGER, 
	"LAST_UPDATE_DTTM" VARCHAR(50), 
	"LAST_UPDATE_INITIALS" VARCHAR(18), 
	PRIMARY KEY ("BAG_ABBREV")
);
INSERT INTO `DS_MAG_BAG` (BAG_ABBREV,BAG_NM,MAGIC_POWER_DESCR,SORT_ORD,LAST_UPDATE_DTTM,LAST_UPDATE_INITIALS) VALUES ('FSH','Fish Sack','','','','');
INSERT INTO `DS_MAG_BAG` (BAG_ABBREV,BAG_NM,MAGIC_POWER_DESCR,SORT_ORD,LAST_UPDATE_DTTM,LAST_UPDATE_INITIALS) VALUES ('ESC','Escalator Bag','','','','');
INSERT INTO `DS_MAG_BAG` (BAG_ABBREV,BAG_NM,MAGIC_POWER_DESCR,SORT_ORD,LAST_UPDATE_DTTM,LAST_UPDATE_INITIALS) VALUES ('CAN','Canoe Case',NULL,NULL,NULL,NULL);
INSERT INTO `DS_MAG_BAG` (BAG_ABBREV,BAG_NM,MAGIC_POWER_DESCR,SORT_ORD,LAST_UPDATE_DTTM,LAST_UPDATE_INITIALS) VALUES ('KAN','Kangaroo Pouch',NULL,NULL,NULL,NULL);
CREATE UNIQUE INDEX ix_dsapp_users_login_id ON dsapp_users (login_id);
CREATE UNIQUE INDEX ix_dsapp_entities_entity_nm ON dsapp_entities (entity_nm);
CREATE UNIQUE INDEX ix_dsapp_entities_ds_table_nm ON dsapp_entities (ds_table_nm);
COMMIT;
